DEPENDS += " zeroc-ice-dev-native "
EXTRANATIVEPATH += " zeroc-ice-dev-native "

ZEROC_ICE_VERSION = "3.6.3"
ZEROC_ICE_SLICE_DIR = "${STAGING_DIR_NATIVE}/usr/share/Ice-${ZEROC_ICE_VERSION}/slice"
ZEROC_ICE_SLICE2CPP = ${STAGING_BINDIR_NATIVE}/slice2cpp
ZEROC_ICE_SLICE2PY = ${STAGING_BINDIR_NATIVE}/slice2py
